apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  tolerations:
  - key: "specialAccess"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
    tolerationSeconds: 15
  restartPolicy: Always
